/**
 * Returns the Arabic name of the Quran chapter for a given chapter_id (0-based).
 * @param chapter_id - The 0-based index of the chapter (0 = الفاتحة, 1 = البقرة, ...)
 * @returns The Arabic name of the chapter, or "" if not found.
 */
export function getQuranChapterNameArabic(chapter_id: number): string {
  switch (chapter_id) {
    case 0:
      return "الفاتحة";
    case 1:
      return "البقرة";
    case 2:
      return "آل عمران";
    case 3:
      return "النساء";
    case 4:
      return "المائدة";
    case 5:
      return "الأنعام";
    case 6:
      return "الأعراف";
    case 7:
      return "الأنفال";
    case 8:
      return "التوبة";
    case 9:
      return "يونس";
    case 10:
      return "هود";
    case 11:
      return "يوسف";
    case 12:
      return "الرعد";
    case 13:
      return "إبراهيم";
    case 14:
      return "الحجر";
    case 15:
      return "النحل";
    case 16:
      return "الإسراء";
    case 17:
      return "الكهف";
    case 18:
      return "مريم";
    case 19:
      return "طه";
    case 20:
      return "الأنبياء";
    case 21:
      return "الحج";
    case 22:
      return "المؤمنون";
    case 23:
      return "النور";
    case 24:
      return "الفرقان";
    case 25:
      return "الشعراء";
    case 26:
      return "النمل";
    case 27:
      return "القصص";
    case 28:
      return "العنكبوت";
    case 29:
      return "الروم";
    case 30:
      return "لقمان";
    case 31:
      return "السجدة";
    case 32:
      return "الأحزاب";
    case 33:
      return "سبأ";
    case 34:
      return "فاطر";
    case 35:
      return "يس";
    case 36:
      return "الصافات";
    case 37:
      return "ص";
    case 38:
      return "الزمر";
    case 39:
      return "غافر";
    case 40:
      return "فصلت";
    case 41:
      return "الشورى";
    case 42:
      return "الزخرف";
    case 43:
      return "الدخان";
    case 44:
      return "الجاثية";
    case 45:
      return "الأحقاف";
    case 46:
      return "محمد";
    case 47:
      return "الفتح";
    case 48:
      return "الحجرات";
    case 49:
      return "ق";
    case 50:
      return "الذاريات";
    case 51:
      return "الطور";
    case 52:
      return "النجم";
    case 53:
      return "القمر";
    case 54:
      return "الرحمن";
    case 55:
      return "الواقعة";
    case 56:
      return "الحديد";
    case 57:
      return "المجادلة";
    case 58:
      return "الحشر";
    case 59:
      return "الممتحنة";
    case 60:
      return "الصف";
    case 61:
      return "الجمعة";
    case 62:
      return "المنافقون";
    case 63:
      return "التغابن";
    case 64:
      return "الطلاق";
    case 65:
      return "التحريم";
    case 66:
      return "الملك";
    case 67:
      return "القلم";
    case 68:
      return "الحاقة";
    case 69:
      return "المعارج";
    case 70:
      return "نوح";
    case 71:
      return "الجن";
    case 72:
      return "المزمل";
    case 73:
      return "المدثر";
    case 74:
      return "القيامة";
    case 75:
      return "الإنسان";
    case 76:
      return "المرسلات";
    case 77:
      return "النبأ";
    case 78:
      return "النازعات";
    case 79:
      return "عبس";
    case 80:
      return "التكوير";
    case 81:
      return "الانفطار";
    case 82:
      return "المطففين";
    case 83:
      return "الإنشقاق";
    case 84:
      return "البروج";
    case 85:
      return "الطارق";
    case 86:
      return "الأعلى";
    case 87:
      return "الغاشية";
    case 88:
      return "الفجر";
    case 89:
      return "البلد";
    case 90:
      return "الشمس";
    case 91:
      return "الليل";
    case 92:
      return "الضحى";
    case 93:
      return "الشرح";
    case 94:
      return "التين";
    case 95:
      return "العلق";
    case 96:
      return "القدر";
    case 97:
      return "البينة";
    case 98:
      return "الزلزلة";
    case 99:
      return "العاديات";
    case 100:
      return "القارعة";
    case 101:
      return "التكاثر";
    case 102:
      return "العصر";
    case 103:
      return "الهمزة";
    case 104:
      return "الفيل";
    case 105:
      return "قريش";
    case 106:
      return "الماعون";
    case 107:
      return "الكوثر";
    case 108:
      return "الكافرون";
    case 109:
      return "النصر";
    case 110:
      return "المسد";
    case 111:
      return "الإخلاص";
    case 112:
      return "الفلق";
    case 113:
      return "الناس";
    default:
      return "";
  }
}
